### ISSUE TITLE
src/python/codemetre/__init__.py ends prematurely

### ISSUE THREAD

**Issue by andistern** [seventh/codemetre#5]
Hi,

getting an IndentationError when trying to install:
python setup.py install
running install
running build
running build_py
running install_lib
byte-compiling /usr/lib/python2.4/site-packages/codemetre/**init**.py to **init**.pyc
Sorry: IndentationError: ('expected an indented block', ('/usr/lib/python2.4/site-packages/codemetre/**init**.py', 161, 35, '        elif name in self._groups:\n'))

trying:
tail codemetre-0.31.1/src/python/codemetre/**init**.py 
            for entry in self._groups[name].entries():
                yield entry
        else:
            raise ValueError("no such name in Project : %s" % name)

```
def entry(self, name):
    if name not in self._names:
        raise ValueError("no such entry in Project : %s" % name)
    elif name in self._groups:
```

regards 

A.

**Comment by seventh** [comment]
python tools are currently being refactored and have been delivered in an unstable state. codemetre 0.31.2 delivers back stable version until refactoring is finished.
